Workaround for collectCoverage() error
Logging in and logging out seems to be causing errors with the coverage collection occuring at the end of the test (with or without instrumentation running).
This issue appears to match documented a documented known issue about page changes: https://github.com/aberonni/nightwatch-coverage#known-limitations

For reference, the error is:
```
{
  sessionId: 'e7e0fe7012747ae3d567402e7ac507b6',
  status: 0,
  value: null
}
   Error: Error while running "execute" command: An error occurred while gathering coverage information
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```